### ISSUE TITLE
Stabilise the API

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#135]
Once everything is stable, we should mark the API as being stable.

This will mean enabling mutation testing (#134) on all builds in CI, and also changing all API guardian `@API` annotations that are currently setting the status attribute as EXPERIMENTAL so that they are STABLE instead.

INTERNAL annotations should stay how they are.

**Comment by sohel-79** [comment]
Hi as #134 is done what about this issue? Can you guide on this one i want to contribute more

**Comment by ascopes** [comment]
Hmm, you could pick this up, yeah. Think it is a good time to be doing it.

Go for it.

**Comment by ascopes** [comment]
Hmm, you could pick this up, yeah. Think it is a good time to be doing it.

Go for it.

It is just a case of finding

```java
@API(since = ..., status = Status.EXPERIMENTAL)
```

and replacing with

```java
@API(since = ..., status = Status.STABLE)
```

...we want to keep anything marked as INTERNAL as it is though.
