### ISSUE TITLE
Fix typo in constant name for module path autofix

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#177]
https://github.com/ascopes/java-compiler-testing/blob/2e1e0edd4e13ddce8e3e85bfbcf6d0668421b979/java-compiler-testing/src/main/java/io/github/ascopes/jct/compilers/JctCompiler.java#L81

There should be an underscore in "MODULE_PATH".

**Comment by sohel-79** [comment]
i have fixed it

**Comment by ascopes** [comment]
@sohel-79 thanks for that, will assign it to you then!
