### ISSUE TITLE
Eclipse fails to load project (write instructions?)

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#226]
![210486160-158716c4-10ce-46d0-9d12-d5510c3a9272](https://user-images.githubusercontent.com/73482956/210509261-3d30ac8a-b15f-4ede-b129-41688e6757be.png)

Seems that there are issues loading this project on Eclipse due to the use of Groovy in the acceptance tests (see #219 for original discussion).

Probably worth investigating this and making a Wiki page describing IDE configuration instructions for contributors.

Instructions for the following are probably useful:

- IntelliJ IDEA
- Eclipse / JBoss Studio
- VS Code
- Fleet(?)
- NetBeans

**Comment by sohel-79** [comment]
I had no issues while loading the project and tried to build it was successful.

**Comment by ascopes** [comment]
@sohel-79 thats great, thanks for checking. What version were you using?

**Comment by sohel-79** [comment]
Maybe 2022-09 not sure

**Comment by ascopes** [comment]
@Badrri-Narayanan what version were you using, out of curiosity?

**Comment by ascopes** [comment]
Going to assume this isn't a widespread issue for now. If there is any further details on this, let me know and I will reopen it!
