### ISSUE TITLE
Investigate Codecov not showing coverage correctly

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#257]
![Screenshot_2023-01-16-08-18-11-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/73482956/212629974-c5e06c35-1523-48e8-93bf-16355c9b4177.jpg)

Seems coverage reports are not rendering.

Could this be to do with the reports being merged that use Windows-style paths on Windows and POSIX-style paths on Linux and MacOS?

How do we fix this?

**Comment by sohel-79** [comment]
Hi, can you check the link below? 

https://docs.codecov.com/docs/unexpected-coverage-changes

**Comment by ascopes** [comment]
Think the issue is more around the file previews not showing up, than the coverage differing :-)

**Comment by sohel-79** [comment]
You were right about the issue i think it's about paths 

https://codecov.freshdesk.com/support/solutions/articles/43000593943-files-not-showing-in-codecov-fixing-paths-

**Comment by ascopes** [comment]
I am wondering if a simpler solution may be just to have a shell script that uses the [JaCoCo CLI](https://www.jacoco.org/jacoco/trunk/index.html)  to merge the reports manually, if possible, and then upload the single report to CodeCov.

Another solution might be to use XSLT to somehow fix the path names if that is the issue.

I'll try making a PR that disables the windows runners (won't merge it, but it should be enough to trigger a new report being made and uploaded). If this shows the file contents on codecov, it means that the Windows-style paths are the issue!

**Comment by ascopes** [comment]
Doesn't seem to be this. I am a bit baffled. Might need to open an issue with CodeCov to get some help on this one.

**Comment by ascopes** [comment]
Seems to have magically fixed itself, weirdly.
