### ISSUE TITLE
Make filemanager.config package part of stable API

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#288]
Update the classes in `java-compiler-testing/src/main/java/io/github/ascopes/jct/filemanagers/config` part of the stable API.

This involves just changing the `@API` annotation on each of the files in this package from reading `status = Status.INTERNAL` to `status = Status.STABLE`.

**Comment by sohel-79** [comment]
@JoePorterDev use intelliJ and with it's find and replace you can do it easily

**Comment by ascopes** [comment]
Assigned, @JoePorterDev. Thanks!
