### ISSUE TITLE
Remove GenericMock

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#308]
In the helper package is a class called `GenericMock`.

https://github.com/ascopes/java-compiler-testing/blob/main/java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/GenericMock.java

Usage of this class looks like the following:

```java
var list = mockRaw(List.class)
    .<List<String>>upcastedTo()
    .build();

var list = mockRaw(List.class)
    .<List<String>>upcastedTo()
    .build(withSettings()...);

// etc
```

Mockito 5.1.0 has additional overloads that I contributed that make the regular mocks work fully with type coercion now. This means that the GenericMock class can be deleted and replaced with calls to Mockito directly. In the above example, the new code would become:

```java
List<String> list = mock();

List<String> list = mock(withSettings()...);

// etc
```

**Comment by piyush280599** [comment]
@ascopes I am new to open source and would like to contribute on this. Can you please assign me this task along with little more guidance so that I can contribute.

**Comment by ascopes** [comment]
@piyush280599 Done!

So pretty much, anywhere that references that class needs to be identified (your IDE should be able to help with that, or you can use SourceGraph: https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fascopes%2Fjava-compiler-testing%24+GenericMock&patternType=standard&sm=1&groupBy=path).

As an example, if you look at https://sourcegraph.com/github.com/ascopes/java-compiler-testing/-/blob/java-compiler-testing/src/test/java/io/github/ascopes/jct/tests/helpers/Fixtures.java?L205&subtree=true

...this:

```java
var mock = mockRaw(TraceDiagnostic.class)
        .<TraceDiagnostic<JavaFileObject>>upcastedTo()
        .build(withSettings().strictness(Strictness.LENIENT));
```

...can be replaced with...

```java
TraceDiagnostic<JavaFileObject> mock = mock(withSettings().strictness(Strictness.LENIENT));
```

where `mock(...)` is defined as part of Mocktio Core over here: https://www.javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html

It is just a case of finding all those mockRaw calls imported from the GenericMock class and replacing them. You can test everything works by running the unit tests with Maven (`./mvnw test -pl java-compiler-testing -am`) or by running them in your IDE.

Once nothing else uses the GenericMock class, it can be deleted entirely.

**Comment by ascopes** [comment]
@piyush280599 how is it going?

**Comment by ascopes** [comment]
@piyush280599 I am going to pick this one up and get it out of the way, since it is a quick change. Hope you don't mind.
