### ISSUE TITLE
Convert Groovy test classes to Java

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#542]
Convert the Groovy acceptance test classes back to Java and remove the dependency on Groovy.

This will help support newer JDK versions sooner (like Java 22).

**Comment by VarunEnishetty** [comment]
@ascopes I would like to work on this task.
Could you please assign it to me and provide a bit more context about this task.

**Comment by ascopes** [comment]
@VarunEnishetty sure thing. Assigned!

If you look in the `acceptance-tests` module, there are a bunch of modules. Many are implemented in Groovy rather than Java. These tests try to compile some sample code in the `resources/` directory. This sample code will relate to a commonly used annotation processor library, and is basically a way of me ensuring the compiler configuration is correct.

What we want to do is rewrite those tests in Java instead (will be a bit more verbose due to how reflection works in Java versus Groovy). You'll need to make use of the java.lang.reflect APIs to translate some of the logic that compiles code and then loads the classes dynamically.

Some of the tests already use Java (I vaguely recall the dogfood test already does this, which is a test that compiles the code in the java-compiler-testing module as a proof that complex code can be compiled via this library).

I'd suggest doing one module at a time to keep it easy to review and easier for you to work on.

Each module will need to pass the build process (`./mvnw clean verify -am -pl <module-name>` should be all you need to run to do this, e.g. `./mvnw clean verify -am -pl acceptance-tests`).

You'll also need to make sure the license headers are in place for that build to work. You can do this automatically by running `./mvnw license:format`.

Let me know if you need any help or have any questions!

**Comment by ascopes** [comment]
@VarunEnishetty how are you getting on? Is there anything else you need clarification on?

**Comment by ascopes** [comment]
If you're still interested in working on this, please let me know. Happy to keep it assigned but if you aren't interested then it enables me or someone else to pick it up when we have time :-)

**Comment by ascopes** [comment]
Going to unassign this, just as I haven't heard back... if you find you have time to pick this up in the future, please let me know. 

Thanks.

**Comment by ascopes** [comment]
Going to pick this up as I have some changes for this on my laptop at home that I will push when I get the time.
