### ISSUE TITLE
Remove asList in IterableUtils

### ISSUE THREAD

**Issue by ascopes** [ascopes/java-compiler-testing#90]
IterableUtils contains two methods that are duplicated. Remove the "asList" method and rewire any usages to use the "combineOneOrMore" method instead.

**Comment by Keerthivardhan1** [comment]
Hi
I am  beginner  to the open source ,I would like to contribute 
can you assign this to me

**Comment by Keerthivardhan1** [comment]
From repo I understood that 
"asList" method is used in 7 different file .
 And I have to replace it with "combineOneOrMore" method  in all that files . is it right

**Comment by ascopes** [comment]
Yep thats right!
